_posts/2015-10-13-meeting.md

Added october 13th 2015 meeting (outside-in tdd)

---

_posts/2016-01-12-meeting.md

My topic in Jan will be redux (from the very beginners view point)

added january 12th 2016 meeting (redux)

---

_posts/2016-05-11-meeting.md

[MAY 11 2016]: ember-redux origin story

---

_posts/2016-10-11-meeting.md

Chuck - I've got what I believe is the correct pizza sponsor/ address but if you need to update this let me know

Oct meeeting 2016: the future!

---

_posts/2017-06-13-meeting.md
_talks/continuous-deployment-of-npm-packages.md

it looks like the tickly info is different for each meeting. i assume you add that after this gets pulled in?

adds details for the june 2017 meeting

---

_posts/2017-07-18-meeting.md
_talks/redux-and-typescript-better-together.md

Chuck/Eric
I've got the basic post up so we can start pushing this on twitter/etc
Feel free to add any additional talks as they come up

added July 18th 2017 details (SourceAllies Sponsor)

---

_posts/2017-08-15-meeting.md
_talks/redux-perf-case-study.md

Redux: A Case Study in Performance Tuning
Sponsor will be Pillar

Aug 15th 2017 topic

---

_talks/redux-perf-case-study.md

@toranb are these the correct links for your talk? anything else you'd want added?

add repo and video links for the redux-perf talk

---

_posts/2017-10-10-meeting.md
_talks/react-in-isolation.md

this still needs tikly, since im still not up to speed on how to add that

Add details for the Oct meeting

---

_talks/codeReview_etc.md

Hi guys, 
Mike Clark asked me about doing a talk. Not specifically js foucused, but would plan to cover some ideas related to linters or the like as well as demo of atom teletype plugin which I have been experimenting with for pair programming

add draft of talk markdown file

---

_posts/2018-06-12-meeting.md
_talks/serverless.md

I assume this is all that's needed to add the talk to the site. Please let me know if there's more that needs to be done.

added serverless talk

---

_talks/this-is-how-i-code.md

Talk Proposal: https://github.com/dsmjs/talk-proposals/issues/10

Add "This Is How I Code" Talk

---

_posts/2018-08-14-meeting.md
_talks/over-mocking-under-delivering.md

@travi here is the baseline PR for my talk in Aug
Any further questions let me know ;)

TALK: Aug 14, 2018 "over mocking, under delivering"

---

_posts/2018-12-11-meeting.md
_talks/_december_2018_no_meeting.md

Simple no meeting post & talk placeholder for Dec 11th 2018.

Added december no meeting talk and post

---

_posts/2019-01-08-meeting.md
_talks/lego_boost.md

Added meeting and talk info for Jan 2019 meeting. 
Presenter: @churchs19 
Host: Source Allies.
Todo: Verify eventbrite. https://www.eventbrite.com/preview?eid=54298495261

Jan2019 talk

---

_posts/2019-05-14-meeting.md
_talks/rest-to-graphql.md

add the information for the GraphQL to REST talk

added rest to graphql talk

---

_posts/2019-08-13-meeting.md
_talks/headless-chrome.md

closes dsmjs/talk-proposals#52

Add August meeting

---

_talks/gatsby-contentful-netlify.md

@micLeners is this the repo i should link to?

Add repo link for the October meeting

---

_posts/2019-11-12-meeting.md
_talks/quokka-wallaby.md

wired up enough to get the meeting to be listed. still needs details about my talk and the eventbrite details

Add november meeting

---

_posts/2020-02-11-meeting.md
_talks/lenderclose.md

I want to get this live. I will go back and add/modify details if/when we get them.

LenderClose 2-2020 meeting

---

_posts/2020-03-10-meeting.md
_talks/oauth-for-authentication-and-authorization.md

Added the March meeting

---

_posts/2020-05-12-meeting.md

since i'm not fully up to speed with the plan, i'm not sure if this is appropriate, but this is the meeting id from https://www.eventbrite.com/e/web-geeksdsmjs-spring-virtual-gathering-tickets-104495843882

Set meeting ID to proper eventbrite meeting
